<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blast Customer - Add</title>
    <?php $this->load->view('css/style_transaksi_front')?>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <!-- <img class="animation__shake" src="<?=base_url('assets/dist/img/loadingicon.png')?>" alt="icon loading" height="auto"> -->
    </div>

    <!-- Navbar -->
    <?php $this->load->view('navbar')?>
    <!-- /.navbar -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" style="margin-left : auto">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-8">
              <h1>Create Blast Customer</h1>
            </div><!-- /.col -->
            <div class="col-sm-4">
              <div class="button-create">
                <a href="<?=site_url('BlastCustomer')?>" class="btn btn-primary" role="button" style="margin-left: -12px;"> <i
                    class="fas fa-reply">
                  </i>
                </a>
              </div>
            </div>
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- SELECT2 EXAMPLE -->
          <div class="card card-default">
            <div class="card-header">
              <!-- /.card-header -->
              <div class="card-body">
                <form action="<?=site_url('BlastCustomer/insert')?>" method="post" enctype="multipart/form-data">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>ID Blast</label>
                          <input class="form-control" disabled placeholder="Generated by System">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Jenis Blast</label>
                          <select class="form-control" name="jenis_blast" id="jenis-blast" style="width: 100%;">
                            <option>-- Pilih Jenis Blast --</option>
                            <option>Announcement</option>
                            <option>Hold Event</option>
                          </select>
                          <!-- <input class="form-control" disabled="disabled" type="text" placeholder="Generated by system"> -->
                        </div>
                      </div>
                    </div>
    
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Tanggal Blast</label>
                          <div class="input-group date" id="tglblast" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" name="tgl_blast" data-target="#tglblast" />
                            <div class="input-group-append" data-target="#tglblast" data-toggle="datetimepicker">
                              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Jenis Paket</label>
                          <select class="form-control" name="jenis" style="width: 100%;">
                            <option>-- Pilih Jenis Paket --</option>
                            <option>All</option>
                            <?php foreach ($jenis as $jenis) {?>
                                <option><?=$jenis['jenis_paket']?></option>
                            <?php } ?>
                          </select>
                        </div>
                      </div>
                    </div>
    
                    <div class="row" id="tanggal-event" style="display:none">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Start Date</label>
                          <div class="input-group date" id="startdate" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" name="start_date_periode" data-target="#startdate" />
                            <div class="input-group-append" data-target="#startdate" data-toggle="datetimepicker">
                              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>End Date</label>
                          <div class="input-group date" id="enddate" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" name="end_date_periode" data-target="#enddate" />
                            <div class="input-group-append" data-target="#enddate" data-toggle="datetimepicker">
                              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
    
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Whatsapp Message</label>
                          <textarea class="form-control" rows="3" name="isi_pesan" placeholder=""></textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                  <hr>
    
                  <div class="row">
                    <div class="col-md-12 text-right">
                      <a href="<?=site_url('BlastCustomer')?>" button type="button" class="btn btn-outline-success"
                        style="margin-right: 10px;">Back</button></a>
                      <button  type="submit" class="btn btn-success swalDefaultSuccess">Save</button>
                    </div>
                  </div>
                </form>
            </div>
      </section>

    <?php $this->load->view('footer')?>
    <?php $this->load->view('js/script_blast')?>

 <!-- Page specific script -->
 <script>
      $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
          theme: 'bootstrap4'
        })

        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
        });

        //Date picker
        $('#tglblast').datetimepicker({
          format: 'DD-MM-YYYY'
        });

        $('#startdate').datetimepicker({
          format: 'DD-MM-YYYY'
        });

        $('#enddate').datetimepicker({
          format: 'DD-MM-YYYY'
        });

        //Date and time picker
        $('#reservationdatetime').datetimepicker({
          icons: {
            time: 'far fa-clock'
          }
        });

        //Date range picker
        $('#reservation').daterangepicker()

        //Date range picker with time picker
        $('#reservationtime').daterangepicker({
          timePicker: true,
          timePickerIncrement: 30,
          locale: {
            format: 'MM/DD/YYYY hh:mm A'
          }
        })

        //Timepicker
        $('#timepicker').datetimepicker({
          format: 'LT'
        })

        //Tooltip
        $(document).ready(function () {
          $('[data-toggle="tooltip"]').tooltip();
        });
      });

    </script>

    <script>
      $(document).ready(function(){
        $('#jenis-blast').change(function(){
          var jenis_blast = $(this).val();
          if (jenis_blast == "Hold Event") {
            document.getElementById("tanggal-event").style.display = "flex";
          } else {
            document.getElementById("tanggal-event").style.display = "none";
          }
        })
      });
    </script>
</body>
</html>