<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Customer Transaction</title>

    <?php $this->load->view('css/style_create')?>
</head>

<body class="hold-transition sidebar-mini layout-navbar-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="<?=base_url('assets/dist/img/loadingicon.png')?>" alt="icon loading"
                height="auto">
        </div>

        <!-- Navbar -->
        <?php $this->load->view('navbar')?>
        <!-- /.navbar -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="margin-left : auto">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-4 mt-4">
                        <div class="col-sm-12">
                            <h1 style="text-align: center;">Customer Detail</h1>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- SELECT2 EXAMPLE -->
                    <div class="card card-default">
                        <div class="card-header">
                            <!-- /.card-header -->
                            <form action="<?=site_url('transaksi/dataCustomer')?>" enctype="multipart/form-data"
                                autocomplete="off" method="post" name="form">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>ID User</label>
                                                <input class="form-control" disabled="disabled" type="text"
                                                    placeholder="Generated by system">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Status Paket</label>
                                                <select class="form-control select2" id="status_paket"
                                                    name="status_paket" style="width: 100%;">
                                                    <?php if (!empty($this->session->userdata('status_paket'))) { ?>
                                                    <option value="<?=$this->session->userdata('status_paket')?>">
                                                        <?=$this->session->userdata('status_paket')?></option>
                                                    <?php } ?>
                                                    <option>-- Pilih Status Paket --</option>
                                                    <option value="Regular">Regular</option>
                                                    <option value="Promotion">Promotion</option>
                                                    <option value="Hampers">Hampers</option>
                                                    <option value="Corporate">Corporate</option>
                                                    <option value="Staff Meals">Staff Meals</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>New/Existing Customer*</label>
                                                <select class="form-control select2" style="width: 100%;">
                                                    <option selected="selected">New</option>
                                                    <option>Existing</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>ID Transaksi</label>
                                                <input class="form-control" disabled="disabled" type="text"
                                                    placeholder="Generated by system">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Brand</label>
                                                <select class="form-control select2" id="perusahaan" name="brand"
                                                    style="width: 100%;">
                                                    <?php if (!empty($this->session->userdata('id_brand'))) { ?>
                                                    <?php foreach ($brand as $key) { ?>
                                                        <?php if ($this->session->userdata('id_brand') == $key['id_perusahaan']) { ?>
                                                            <option value="<?=$this->session->userdata('id_brand')?>"><?=$key['nama']?></option>
                                                        <?php } ?>
                                                    <?php } ?>
                                                    <!--<option value="<?//=$this->session->userdata('id_brand')?>">Dermaster-->
                                                    <!--</option>-->
                                                    <!--<?php //} else {?>-->
                                                    <!--<option value="<?//=$this->session->userdata('id_brand')?>">Derma-->
                                                    <!--    Express</option>-->
                                                    <!--<?php// }?>-->
                                                    <?php } ?>
                                                    <option value="">-- Select Brand --</option>
                                                    <?php foreach ($brand as $brand) { ?>
                                                    <option value="<?=$brand['id_perusahaan']?>"><?=$brand['nama']?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Klinik</label>
                                                <select class="form-control select2" name="id_klinik" id="klinik"
                                                    style="width: 100%;">
                                                    <?php if (!empty($this->session->userdata('id_klinik'))) { ?>
                                                    <option value="<?=$this->session->userdata('id_klinik')?>">
                                                        <?=$this->session->userdata('nama_klinik')?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>ID Customer</label>
                                                <?php if (!empty($this->session->userdata('id_cust'))) { ?>
                                                <input class="form-control" name="id_customer" id="id_customer"
                                                    type="text" value="<?=$this->session->userdata('id_cust')?>" required>
                                                <?php } else {?>
                                                <input class="form-control" name="id_customer" id="id_customer"
                                                    type="text" placeholder="Generated by system" required>
                                                <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Nama Customer</label>
                                                <?php if (!empty($this->session->userdata('nama_cust'))) { ?>
                                                <input class="form-control" name="nama_customer" id="nama_customer"
                                                    type="text" value="<?=$this->session->userdata('nama_cust')?>">
                                                <?php } else {?>
                                                <input class="form-control" name="nama_customer" id="nama_customer"
                                                    type="text" placeholder="">
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Nomer Whatsapp<span style="color:red">*</span></label>
                                                <?php if (!empty($this->session->userdata('telp_1'))) { ?>
                                                <input class="form-control" id="telp_1" name="telp_1" maxlength="13"
                                                    onkeypress="return hanyaAngka(event)" type="text"
                                                    value="<?=$this->session->userdata('telp_1')?>">
                                                <?php } else {?>
                                                <input class="form-control" id="telp_1" name="telp_1" maxlength="13"
                                                    onkeypress="return hanyaAngka(event)" type="text" placeholder="">
                                                <?php } ?>
                                                <!-- <input class="form-control" type="text" name="telp_1" maxlength="13" onkeypress="return hanyaAngka(event)" placeholder=""> -->
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Nomer Telephone</label>
                                                <?php if (!empty($this->session->userdata('telp_2'))) { ?>
                                                <input class="form-control" id="telp_2" name="telp_2" maxlength="13"
                                                    onkeypress="return hanyaAngka(event)" type="text"
                                                    value="<?=$this->session->userdata('telp_2')?>">
                                                <?php } else {?>
                                                <input class="form-control" id="telp_2" name="telp_2" maxlength="13"
                                                    onkeypress="return hanyaAngka(event)" type="text" placeholder="">
                                                <?php } ?>
                                                <!-- <input class="form-control" type="text" name="telp_2" maxlength="13" onkeypress="return hanyaAngka(event)" placeholder=""> -->
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Tanggal Transaksi</label>
                                                <div class="input-group date" id="reservationdate"
                                                    data-target-input="nearest">
                                                    <?php if (!empty($this->session->userdata('tgl_trans'))) { ?>
                                                    <input type="text" id="tgl_trans" name="tgl_trans"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#reservationdate"
                                                        value="<?=$this->session->userdata('tgl_trans')?>" />
                                                    <div class="input-group-append" data-target="#reservationdate"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-calendar"></i>
                                                        </div>
                                                    </div>
                                                    <?php } else {?>
                                                    <input type="text" id="tgl_trans" name="tgl_trans"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#reservationdate" value="<?=date('d-m-Y')?>" />
                                                    <div class="input-group-append" data-target="#reservationdate"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-calendar"></i>
                                                        </div>
                                                    </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                            <!-- /.form-group -->
                                        </div>
                                        <!-- /.col -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Waktu Transaksi</label>
                                                <div class="input-group date" id="timepicker"
                                                    data-target-input="nearest">
                                                    <?php if (!empty($this->session->userdata('waktu_trans'))) { ?>
                                                    <input type="text" id="waktu_trans" name="waktu_trans"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#timepicker"
                                                        value="<?=$this->session->userdata('waktu_trans')?>" />
                                                    <div class="input-group-append" data-target="#timepicker"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="far fa-clock"></i></div>
                                                    </div>
                                                    <?php } else {?>
                                                    <input type="text" id="waktu_trans" name="waktu_trans"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#timepicker" value="<?=date('H:i')?>" />
                                                    <div class="input-group-append" data-target="#timepicker"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="far fa-clock"></i></div>
                                                    </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Tanggal Pembayaran</label>
                                                <div class="input-group date" id="reservationdate2"
                                                    data-target-input="nearest">
                                                    <?php if (!empty($this->session->userdata('tgl_pembayaran'))) { ?>
                                                    <input type="text" id="tgl_pembayaran" name="tgl_pembayaran"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#reservationdate2"
                                                        value="<?=$this->session->userdata('tgl_pembayaran')?>" />
                                                    <div class="input-group-append" data-target="#reservationdate2"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-calendar"></i>
                                                        </div>
                                                    </div>
                                                    <?php } else {?>
                                                    <input type="text" id="tgl_pembayaran" name="tgl_pembayaran"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#reservationdate2" value="<?=date('d-m-Y')?>" />
                                                    <div class="input-group-append" data-target="#reservationdate2"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-calendar"></i>
                                                        </div>
                                                    </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                            <!-- /.form-group -->
                                        </div>
                                        <!-- /.col -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Waktu Pembayaran</label>
                                                <div class="input-group date" id="timepicker2"
                                                    data-target-input="nearest">
                                                    <?php if (!empty($this->session->userdata('waktu_pembayaran'))) { ?>
                                                    <input type="text" id="waktu_pembayaran" name="waktu_pembayaran"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#timepicker2"
                                                        value="<?=$this->session->userdata('waktu_trans')?>" />
                                                    <div class="input-group-append" data-target="#timepicker2"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="far fa-clock"></i></div>
                                                    </div>
                                                    <?php } else {?>
                                                    <input type="text" id="waktu_pembayaran" name="waktu_pembayaran"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#timepicker2" value="<?=date('H:i')?>" />
                                                    <div class="input-group-append" data-target="#timepicker2"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="far fa-clock"></i></div>
                                                    </div>
                                                    <?php } ?>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Status Pembayaran</label>
                                                <!-- <div class="input-group date" id="reservationdate" data-target-input="nearest"> -->
                                                <!-- <input type="text" class="form-control" name="status_pembayaran" readonly value="Lunas"> -->
                                                <select name="status_pembayaran" id="status_pembayaran"
                                                    class="form-control select2" style="width: 100%;">
                                                    <option value="Lunas">Lunas</option>
                                                    <option value="Belum Lunas">Belum Lunas</option>
                                                </select>
                                                <!-- <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker"> -->
                                                <!-- </div> -->
                                                <!-- </div> -->
                                            </div>
                                            <!-- /.form-group -->
                                        </div>
                                        <!-- /.col -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Status Verifikasi</label>
                                                <!-- <div class="input-group date" id="timepicker" data-target-input="nearest"> -->
                                                <input type="text" name="status_verifikasi" id="status_verifikasi"
                                                    class="form-control" value="Not Verified" readonly>
                                                <!-- <select class="form-control select2" name="status_verifikasi" style="width: 100%;">
                          <option value=""></option>
                          <option value="verified">Verified</option>
                        </select> -->
                                                <!-- <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                        </div> -->
                                                <!-- </div> -->
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Qty Total</label>
                                                <input class="form-control" type="text" id="qty_total" readonly
                                                    name="qty_total" value="<?=$qty_total?>" placeholder="Pack..">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Remarks</label>
                                                <input class="form-control" name="remarks" id="remarks" type="text"
                                                    placeholder="">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="card-title">Detail Transaksi</h3>
                                                <div class="card-tools">
                                                    <div class="input-group input-group-sm" style="width: 50px;">
                                                        <div class="input-group-append">
                                                            <button type="submit" class="btn btn-primary"
                                                                data-toggle="tooltip" title="Create">
                                                                <i class="fas fa-plus"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                            </form>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>ID Transaksi</th>
                                            <th>Kategori Paket</th>
                                            <th>Jenis Paket</th>
                                            <th>Waktu Paket</th>
                                            <th>Qty Paket</th>
                                            <th>Periode Paket</th>
                                            <th>Detail Paket</th>
                                            <!-- <th>Status Pembayaran</th> -->
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (empty($cart)) { ?>
                                        <tr>
                                            <td colspan="8"><i> Tidak Ada Data</i></td>
                                        </tr>
                                        <?php }
                          foreach ($cart as $key) {?>
                                        <tr>
                                            <td><?=$key['id']?></td>
                                            <td><?=$key['kategori_paket']?></td>
                                            <td><?=$key['jenis_paket']?></td>
                                            <td><?=$key['waktu_paket']?></td>
                                            <td><?=$key['qty_paket']?></td>
                                            <td><?=$key['periode_paket']?></td>
                                            <td><?=$key['detail_paket']?></td>
                                            <!-- <td> Lunas</td> -->
                                            <td>
                                                <div class="btn-group btn-group-xs">
                                                    <a href="#" class="btn btn-info" data-toggle="tooltip"
                                                        title="View"><i class="fas fa-eye"></i></a>
                                                    <a href="#" class="btn btn-warning" data-toggle="tooltip"
                                                        title="Create"><i class="fas fa-pencil-alt"></i></a>
                                                    <a href="<?=site_url('transaksi/removefromcart/'.$key['rowid'])?>"
                                                        class="btn btn-danger" data-toggle="tooltip" title="Delete"><i
                                                            class="fas fa-trash"></i></a>
                                                </div>
                                        </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                                <hr>
                                <!-- stop delivery form -->
                                <!-- <div class="row">
                                    <div class="col-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="card-title">Stop Delivery</h3>
                                            </div>
                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="button-create">
                                                        <a class="btn btn-primary" data-toggle="tooltip" title="Add"
                                                            href="stop-delivery.html" role="button"
                                                            style="margin-top: 10px;"> <i class="fas fa-plus">
                                                            </i>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div> -->
                                            <!-- /.card-header -->
                                            <!-- <div class="card-body">
                                                <table class="table table-bordered table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>ID Transaksi</th>
                                                            <th>Start Hold</th>
                                                            <th>End Hold Delivery</th>
                                                            <th>Start Delivery</th>
                                                            <th>Keterangan</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td colspan="6"><i> Tidak Ada Data</i></td>
                                                        </tr> -->
                                                        <!-- <tr>
                            <td>Del001</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>Isi keterangan</td>
                            <td>
                              <div class="btn-group btn-group-xs">
                                <a href="#" class="btn btn-info" data-toggle="tooltip" title="View"><i
                                    class="fas fa-eye"></i></a>
                                <a href="#" class="btn btn-warning" data-toggle="tooltip" title="Create"><i
                                    class="fas fa-pencil-alt"></i></a>
                                <a href="#" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i
                                    class="fas fa-trash"></i></a>
                              </div>
                          </tr>
                          <tr>
                            <td>Del001</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>Isi keterangan</td>
                            <td>
                              <div class="btn-group btn-group-xs">
                                <a href="#" class="btn btn-info" data-toggle="tooltip" title="View"><i
                                    class="fas fa-eye"></i></a>
                                <a href="#" class="btn btn-warning" data-toggle="tooltip" title="Create"><i
                                    class="fas fa-pencil-alt"></i></a>
                                <a href="#" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i
                                    class="fas fa-trash"></i></a>
                              </div>
                            </td>
                          </tr> -->
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div> <!-- div close tabel stop delivery -->
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-12 text-right">
                                                <button type="button" class="btn btn-outline-success" onclick="backConfirm('<?=site_url('transaksi')?>')"
                                                    style="margin-right: 10px;">Back</button>
                                                    <?php if (empty($cart)) { ?>
                                                      <button type="button" class="btn btn-success" onclick="saveConfirm()">Save</button>
                                                    <?php } else {?>
                                                      <button onclick="save('<?=site_url('transaksi/insert_trans')?>')" type="button" class="btn btn-success">Save</button>
                                                    <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- </form> -->
                            </div>
                        </div>
                    </div> <!-- close div container fluid -->



                    <!-- /.modal detail paket-->

                    <!-- /.close div modal detail transaksi -->
            </section>

            <?php $this->load->view('footer')?>
            <?php $this->load->view('js/script_create')?>
            <?php $this->load->view('modal')?>

            <script>
            function hanyaAngka(evt) {
                var charCode = (evt.which) ? evt.which : event.keyCode
                if (charCode > 31 && (charCode < 48 || charCode > 57))

                    return false;
                return true;
            }
            </script>

            <script>
            // var form = document.getElementById("user");
            // document.getElementById("datacust").addEventListener("click", function () {
            //   console.log(form.submit());
            //   // form.submit();
            // });
            </script>
            <script>
            $(document).ready(function() {
                $('#perusahaan').change(function() {
                    var perusahaan = $(this).val();
                    $.ajax({
                        type: "POST",
                        url: "<?=site_url('transaksi/getklinik')?>",
                        data: {
                            perusahaan: perusahaan
                        },
                        success: function(response) {
                            // alert(response);
                            $('#klinik').html(response);
                            $('#klinik').selectpicker('refresh');
                        }
                    })
                })
            })
            </script>

            <script>
            function backConfirm(url) {
                $('#btn-back').attr('href', url);
                $('#backModal').modal();
            }

            function saveConfirm(url) {
                $('#saveModal').modal();

                // $('#btn-save').attr('url', save(url));
            }
            </script>
            <script>
            function save(url) {
                var status_paket = document.forms["form"]["status_paket"].value;
                var brand = document.forms["form"]["perusahaan"].value;
                var id_klinik = document.forms["form"]["id_klinik"].value;
                var id_customer = document.forms["form"]["id_customer"].value;
                var nama_customer = document.forms["form"]["nama_customer"].value;
                var telp_1 = document.forms["form"]["telp_1"].value;
                var telp_2 = document.forms["form"]["telp_2"].value;
                var tgl_trans = document.forms["form"]["tgl_trans"].value;
                var waktu_trans = document.forms["form"]["waktu_trans"].value;
                var tgl_pembayaran = document.forms["form"]["tgl_pembayaran"].value;
                var waktu_pembayaran = document.forms["form"]["waktu_pembayaran"].value;
                var status_pembayaran = document.forms["form"]["status_pembayaran"].value;
                var status_verifikasi = document.forms["form"]["status_verifikasi"].value;
                var qty_total = document.forms["form"]["qty_total"].value;
                var remarks = document.forms["form"]["remarks"].value;
                if ((status_paket == "" || status_paket == "-- Pilih Status Paket --") && (brand == "" || brand ==
                        "-- Select Branch --") && (id_klinik == "" || id_klinik == "- Pilih Klinik -" || id_klinik ==
                        null) && (id_customer == null || id_customer == "") && (nama_customer == null ||
                        nama_customer == "") && (telp_1 == null || telp_1 == "") && (telp_2 == null || telp_2 == "")) {
                    $('#saveModal').modal('hide');
                    $('#validateForm').modal();
                } else {
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: {
                            id_brand: brand,
                            status_paket: status_paket,
                            id_klinik: id_klinik,
                            id_cust: id_customer,
                            nama_cust: nama_customer,
                            telp_1: telp_1,
                            telp_2: telp_2,
                            tgl_trans: tgl_trans,
                            waktu_trans: waktu_trans,
                            tgl_pembayaran: tgl_pembayaran,
                            waktu_pembayaran: waktu_pembayaran,
                            status_pembayaran: status_pembayaran,
                            status_verifikasi: status_verifikasi,
                            qty_total: qty_total,
                            remarks: remarks
                        },
                        success : function(response){
                            window.location.href = '<?=site_url('transaksi')?>';
                        }
                    })
                }
            }
            </script>
</body>

</html>